export enum RoutePaths {
  ABOUT = '/staff',
  VACANCYLIST = 'vacancy',
  EMPLOYEES = 'employees',
  VACANCY = 'vacancy/:vacancyId',
  PAGE404 = '*',
  LOGIN = 'login',
  MENU = 'menu',
  PLANS = 'plans',
  PLAN = 'plans/:id',
  CREATE_PLANS = 'plans/create',
  EDIT_PLAN = '/plans/:id/edit',
  CREATE_SCHEDULE = 'schedule/create',
  EDIT_SCHEDULE = 'schedule/edit:id',
  SCHEDULES = 'schedules',
}
