export enum RoutePaths {
  ABOUT = '/staff',
  VACANCYLIST = 'vacancy',
  EMPLOYEES = 'employees',
  VACANCY = 'vacancy/:vacancyId',
  PAGE404 = '*',
  LOGIN = 'login',
  MENU = 'menu',
  PLANS = 'plans',
  PLAN = 'plans/:id',
  CREATE_PLANS = 'plans/create',
  CREATE_SCHEDULE = 'schedules/create',
  EDIT_SCHEDULE = 'schedules/:id',
  SCHEDULES = 'schedules',
  CREATE_BUS_ROUTE = 'busRoutes/create',
  BUS_ROUTES = 'busRoutes',
  EDIT_BUS_ROUTE = 'busRoutes/:id',
}
